---
title: "News"
---

Stay updated with the latest developments in our interest group and the contributions of our members to the statistical data privacy landscape. From new papers to insightful talks, find out what’s new in our community.

Our [Google Group](https://groups.google.com/g/amstat-pcig-membership) (accessible by members only) has additional news, updates and discussions from PCIG.

### Feed

| Date/Event | News Item |
|------------|-----------|
| Call for Papers | The *International Journal of Population Data Science* (IJPDS) invites submissions for a special issue dedicated to *Privacy Enhancing Technologies (PETs) for Population-Scale Data Use*. See [here for more information](https://ijpds.org/calls/privacy-enhancing-technologies). |
| Elections 2025 -- Results | We are happy to announce the following election results and congrats to elected officers: Joshua Snoke (Chair-Elect); Matthew Williams (Program Chair-Elect); and James Bailie (Communications Chair). Thank you for casting your votes during the PCIG 2025 election. Thanks also to our Elections Committee Member, Monika Hu, for organizing the vote. | 
| Elections 2025 -- Now Open | Voting for PCIG officer positions is currently open. PCIG members should have received a link to vote [via email](https://groups.google.com/g/amstat-pcig-membership/c/DP4JMlRKpjE). (Please [contact us](/contact.html) if you haven't.) Voting closes November 21. We will be calling for nominations to [our various committees](/about.html#leadership-committees-2025) soon. |
| Elections 2024 -- Results | Congratulations to our new officers: Saki Kinney (Chair); Carlos Soto (Chair-Elect); Michael Hawes (Program Chair); Gary Howarth (Program Chair-Elect); and Minsun Riddles (Secretary). Thanks to our Elections Chair, Aref Dajani, for organizing the vote. | 
| JSM 2023 | The ASA Privacy & Confidentiality Interest Group, initiated by [Saki Kinney](https://www.linkedin.com/in/saki-kinney-7236324/) and [Claire McKay Bowen](https://clairemckaybowen.com), was approved by the ASA Council of Sections Governing Board. |
